#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

REPORT_DIR="${DUTY_LIVE_READINESS_REPORT_DIR:-}"
OUTPUT_PATH=""
TITLE="Live Go/No-Go Board"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/security/render-live-go-no-go-board.sh \
    [--report-dir <path>] \
    [--output <markdown_path>] \
    [--title <text>]

What it does:
  - Reads a live-readiness bundle generated by final-live-readiness.sh
  - Produces a markdown board with automated status, evidence paths, and manual gates

Defaults:
  - --report-dir: latest directory under storage/app/live-readiness
  - --output: prints to stdout when omitted
USAGE
}

json_field() {
  local file="$1"
  local field="$2"

  php -r '
    $file = $argv[1];
    $field = $argv[2];
    $raw = @file_get_contents($file);
    if ($raw === false) {
      exit(1);
    }
    $json = json_decode($raw, true);
    if (!is_array($json)) {
      exit(1);
    }
    $segments = explode(".", $field);
    $cursor = $json;
    foreach ($segments as $segment) {
      if ($segment === "") {
        continue;
      }
      if (is_array($cursor) && ctype_digit($segment)) {
        $segment = (int) $segment;
      }
      if (!is_array($cursor) || !array_key_exists($segment, $cursor)) {
        exit(0);
      }
      $cursor = $cursor[$segment];
    }
    if (is_array($cursor)) {
      echo json_encode($cursor, JSON_UNESCAPED_SLASHES);
      exit(0);
    }
    if (is_bool($cursor)) {
      echo $cursor ? "true" : "false";
      exit(0);
    }
    echo (string) $cursor;
  ' "$file" "$field" 2>/dev/null || true
}

status_badge() {
  local value="$1"
  case "$value" in
    passed|GO) printf 'GREEN' ;;
    failed|NO-GO) printf 'RED' ;;
    not_run|'') printf 'GRAY' ;;
    *) printf 'YELLOW' ;;
  esac
}

status_label() {
  local value="$1"
  case "$value" in
    passed) printf 'Passed' ;;
    failed) printf 'Failed' ;;
    not_run|'') printf 'Not run' ;;
    GO) printf 'GO' ;;
    NO-GO) printf 'NO-GO' ;;
    *) printf '%s' "$value" ;;
  esac
}

latest_report_dir() {
  local base_dir="${ROOT_DIR}/storage/app/live-readiness"
  if [[ ! -d "${base_dir}" ]]; then
    return 1
  fi

  ls -1dt "${base_dir}"/* 2>/dev/null | head -n 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --report-dir)
      REPORT_DIR="$2"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --title)
      TITLE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[render-live-go-no-go-board] Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${REPORT_DIR}" ]]; then
  REPORT_DIR="$(latest_report_dir || true)"
fi

if [[ -z "${REPORT_DIR}" || ! -d "${REPORT_DIR}" ]]; then
  echo "[render-live-go-no-go-board] Could not find a live readiness report directory."
  exit 1
fi

SUMMARY_FILE="${REPORT_DIR}/summary.json"
README_FILE="${REPORT_DIR}/README.md"

if [[ ! -f "${SUMMARY_FILE}" ]]; then
  echo "[render-live-go-no-go-board] Missing summary.json in ${REPORT_DIR}"
  exit 1
fi

STARTED_AT="$(json_field "${SUMMARY_FILE}" started_at)"
FINISHED_AT="$(json_field "${SUMMARY_FILE}" finished_at)"
BASE_URL="$(json_field "${SUMMARY_FILE}" base_url)"
ENV_FILE="$(json_field "${SUMMARY_FILE}" env_file)"
FINAL_SCOPE="$(json_field "${SUMMARY_FILE}" final_scope)"
AUTH_MODE="$(json_field "${SUMMARY_FILE}" auth_mode)"
STRIPE_SCOPE_STATUS="$(json_field "${SUMMARY_FILE}" stripe_scope_status)"
FINAL_SCOPE_STATUS="$(json_field "${SUMMARY_FILE}" final_scope_status)"
AUTOMATED_RECOMMENDATION="$(json_field "${SUMMARY_FILE}" automated_recommendation)"
EXIT_CODE="$(json_field "${SUMMARY_FILE}" exit_code)"
MANUAL_EVIDENCE_PATH="$(json_field "${SUMMARY_FILE}" manual_evidence_path)"

STRIPE_LOG="${REPORT_DIR}/stripe-scope.log"
FINAL_LOG="${REPORT_DIR}/${FINAL_SCOPE}-scope.log"

readme_status='Missing'
if [[ -f "${README_FILE}" ]]; then
  readme_status='Present'
fi

stripe_log_label='not generated'
if [[ -f "${STRIPE_LOG}" ]]; then
  stripe_log_label="${STRIPE_LOG}"
fi

final_log_label='not generated'
if [[ -f "${FINAL_LOG}" ]]; then
  final_log_label="${FINAL_LOG}"
fi

manual_evidence_label='not generated'
if [[ -n "${MANUAL_EVIDENCE_PATH}" && -f "${MANUAL_EVIDENCE_PATH}" ]]; then
  manual_evidence_label="${MANUAL_EVIDENCE_PATH}"
fi

rendered="$(cat <<EOF
# ${TITLE}

- Report dir: ${REPORT_DIR}
- Started at (UTC): ${STARTED_AT:-unknown}
- Finished at (UTC): ${FINISHED_AT:-unknown}
- Base URL: ${BASE_URL:-unknown}
- Env file: ${ENV_FILE:-unknown}
- Final scope: ${FINAL_SCOPE:-unknown}
- Auth mode: ${AUTH_MODE:-unknown}
- Automated recommendation: **$(status_label "${AUTOMATED_RECOMMENDATION}")**
- Exit code: ${EXIT_CODE:-unknown}

## Automated Status

| Check | Status | Evidence |
| --- | --- | --- |
| Stripe scope | $(status_label "${STRIPE_SCOPE_STATUS}") | ${STRIPE_LOG} |
| Final scope (${FINAL_SCOPE:-unknown}) | $(status_label "${FINAL_SCOPE_STATUS}") | ${FINAL_LOG} |
| Summary bundle | ${readme_status} | ${README_FILE} |
| Manual evidence template | $([[ "${manual_evidence_label}" != "not generated" ]] && printf 'Present' || printf 'Missing') | ${manual_evidence_label} |

## Decision Snapshot

- Automated verdict badge: $(status_badge "${AUTOMATED_RECOMMENDATION}")
- Stripe scope badge: $(status_badge "${STRIPE_SCOPE_STATUS}")
- Final scope badge: $(status_badge "${FINAL_SCOPE_STATUS}")

## Manual Gates Still Required

- [ ] Confirmar secretos reales de Stripe/Firebase cargados e invalidados.
- [ ] Confirmar base URL final y ventana operativa aprobada.
- [ ] Ejecutar QA manual live minima:
  - [ ] login/session
  - [ ] checkout mixto real
  - [ ] wallet + topup real
  - [ ] reservas y abonos
  - [ ] marketplace
  - [ ] scanner
  - [ ] account center
  - [ ] create/edit event profesional
- [ ] Guardar evidencia humana adicional:
  - [ ] capturas o notas
  - [ ] responsable de la rotacion
  - [ ] decision final go/no-go firmada

## Evidence Bundle

- Summary JSON: ${SUMMARY_FILE}
- README: ${README_FILE}
- Stripe scope log: ${stripe_log_label}
- Final scope log: ${final_log_label}
- Manual evidence: ${manual_evidence_label}

## References

- /Users/monkeyinteractive/DEV/v2/docs/security-rotation-checklist-2026-03-09.md
- /Users/monkeyinteractive/DEV/v2/docs/sprint-1-live-cutover-checklist-2026-03-18.md
- /Users/monkeyinteractive/DEV/v2/docs/qa-manual-lanzamiento-local-2026-03-12.md
EOF
)"

if [[ -n "${OUTPUT_PATH}" ]]; then
  mkdir -p "$(dirname "${OUTPUT_PATH}")"
  printf '%s\n' "${rendered}" > "${OUTPUT_PATH}"
  echo "[render-live-go-no-go-board] Wrote ${OUTPUT_PATH}"
else
  printf '%s\n' "${rendered}"
fi
