<?php

return array(
  'PUBLIC_API_BASE' => 'https://v2.duty.do/pgw',
  'AUTHORIZE_LOGIN_ID' => '3Ca5hYQ6h',
  'AUTHORIZE_TRANSACTION_KEY' => '8bt8Kr5gPZ3ZE23C',
  'AUTHORIZE_ENV' => 'sandbox',
  'STRIPE_SECRET_KEY' => 'sk_test_51Qsd1rPvUycBozh2CRqY9XCE715ohMzCX0gxNiK2fSYGvfZziJOGlEBkAC9q6CDDqIA6puzNiZFFzgz0XQg4iWzU00eXUbJGp5',
  'MIDTRANS_SERVER_KEY' => 'rr',
  'MIDTRANS_BASE' => 'https://app.midtrans.com/snap/v1/transactions',
  'MOLLIE_API_KEY' => 'rr',
  'MYFATOORAH_API_KEY' => 'rr',
  'MYFATOORAH_BASE' => 'https://api.myfatoorah.com',
  'XENDIT_SECRET_KEY' => 'rr',
  'XENDIT_BASE' => 'https://api.xendit.co',
  'FLW_SECRET_KEY' => 'rr',
  'FLW_BASE' => 'https://api.flutterwave.com',
  'PAYPAL_CLIENT_ID' => 'rr',
  'PAYPAL_SECRET' => 'rr',
  'PAYPAL_BASE' => 'https://api-m.paypal.com',
  'PHONEPE_BASE' => 'https://api.phonepe.com/apis/hermes',
  'PHONEPE_MERCHANT_ID' => 'rr',
  'PHONEPE_SALT_KEY' => 'rr',
  'PHONEPE_SALT_INDEX' => '1',
  'MP_ACCESS_TOKEN' => 'rr',
  'MP_BASE' => 'https://api.mercadopago.com',
  'PAYSTACK_SECRET_KEY' => 'rr',
  'PAYSTACK_BASE' => 'https://api.paystack.co',
  'TOYYIBPAY_BASE' => 'https://www.toyyibpay.com',
  'TOYYIBPAY_SECRET_KEY' => 'rr',
  'TOYYIBPAY_CATEGORY_CODE' => 'rr',
  'MONNIFY_BASE' => 'https://api.monnify.com',
  'MONNIFY_API_KEY' => 'rr',
  'MONNIFY_SECRET_KEY' => 'rr',
  'MONNIFY_CONTRACT_CODE' => '1',
  'NOWPAYMENTS_API_KEY' => 'rr',
  'NOWPAYMENTS_BASE' => 'https://api.nowpayments.io/v1',
);
